language: python
sudo: false
dist: trusty

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install codecov
  - pip install coverage
# command to run tests
script:
  - python setup.py test
