__version__ = '0.0.1'
__author__ = 'Hydrospheredata'
__author_email__ = 'info@hydrosphere.io'
__title__ = 'mist-cli'
__description__ = 'Mist command line tool'
__url__ = 'https://hydrosphere.io/mist'
__license__ = 'Apache 2.0'
__copyright__ = '2017 Hydrosphere, Inc. All Rights Reserved'
